# This is a basic workflow to help you get started with Actions

name: Translate to Dutch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "quote" ]
  pull_request:
    branches: [ "quote" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.2.0
      - name: Setup Python
        with:
          python-version: 3.10
      - run: pip3 install googletrans
      
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.2.0
      - name: Run Python
        with:
          python-version: 3.10
      - run: python main.py
